name: 'Prepare node cache'
description: 'Prepare node cache'

inputs:
  working-directory:
    description: 'the working directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout and apply dot-env file
      uses: patternbox/you-build-it-you-run-it/.github/actions/checkout-with-dotenv@main

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: ${{ inputs.working-directory }}
        package-lock-json: ${{ inputs.working-directory }}/package-lock.json
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles( env.package-lock-json ) }}
        path: |
          ~/.npm
          ${{ inputs.working-directory }}/node_modules
