name: "10 - CI/CD (Infrastructure)  🚀"

on:
  push:
    branches: [ main ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    paths:
      - '.github/actions/**'
      - '.github/workflows/1[0-9]*'
      - 'aws-infra/**'
  workflow_dispatch:
    inputs:
      DEVELOP_ACCOUNT_ID:
        description: Overwrite develop account ID
        required: false
        type: string
      PRODUCTION_ACCOUNT_ID:
        description: Overwrite production account ID
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/11-validate-templates.yml
    secrets: inherit

  bootstrap-develop-account:
    name: Develop
    needs: [ run-tests ]
    uses: ./.github/workflows/12-bootstrap-account.yml
    secrets: inherit
    with:
      stage-env: 'DEVELOP'

  bootstrap-production-account:
    name: Production
    if: false
    needs: [ bootstrap-develop-account ]
    uses: ./.github/workflows/12-bootstrap-account.yml
    secrets: inherit
    with:
      stage-env: 'PRODUCTION'
