name: "20 - CI/CD (Application)  🎯"

on:
  push:
    branches: [ main ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    paths:
      - '.github/actions/**'
      - '.github/workflows/2[0-9]*'
      - 'chatapp-infra/**'
      - 'chatapp-ui/**'
  pull_request:
    types: [ closed ]
  workflow_dispatch:
    inputs:
      DEVELOP_ACCOUNT_ID:
        description: Overwrite develop account ID
        required: false
        type: string
      PRODUCTION_ACCOUNT_ID:
        description: Overwrite production account ID
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: Test-and-Build
    uses: ./.github/workflows/21-test-chatapp.yml
    secrets: inherit

  build-app:
    name: Test-and-Build
    needs: [ run-tests ]
    uses: ./.github/workflows/22-build-chatapp.yml
    secrets: inherit
    with:
      stage-env: 'DEVELOP'

  publish-app:
    name: Develop
    needs: [ build-app ]
    uses: ./.github/workflows/23-publish-chatapp.yml
    secrets: inherit
    with:
      stage-env: 'DEVELOP'
