name: "21 --- [ Test Application ]"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  TARGET_ACCOUNT_ID: ${{ inputs.DEVELOP_ACCOUNT_ID || secrets.DEVELOP_ACCOUNT_ID }}

jobs:
  validate-cfn-templates:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Validate CFN templates
        uses: ./.github/actions/run-cfn-script@main
        with:
          script-file: ./chat-infra/validate_cfn_templates.sh

  test-chatapp-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: patternbox/you-build-it-you-run-it/.github/actions/prepare-node-cache@main
        with:
          cache-name: cache-node-modules-cdk

      - name: Install dependencies
        working-directory: chatapp-infra
        run: |
          npm ci
