name: "21 --- [ Test Application ]"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  TARGET_ACCOUNT_ID: ${{ inputs.DEVELOP_ACCOUNT_ID || secrets.DEVELOP_ACCOUNT_ID }}

jobs:
  test-chatapp-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: patternbox/you-build-it-you-run-it/.github/actions/prepare-node-cache@main
        with:
          cache-name: cache-node-modules-cdk

      - name: Install dependencies
        working-directory: chatapp-infra
        run: |
          npm ci

      - name: Run tests
        working-directory: chatapp-infra
        run: |
          npm test

  test-chatapp-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: patternbox/you-build-it-you-run-it/.github/actions/prepare-node-cache@main
        with:
          cache-name: cache-node-modules-ui

      - name: Install dependencies
        working-directory: chatapp-ui
        run: |
          npm ci

      - name: Run tests
        working-directory: chatapp-ui
        run: |
          npm test
