name: "21 --- [ Test Application ]"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  TARGET_ACCOUNT_ID: ${{ inputs.DEVELOP_ACCOUNT_ID || secrets.DEVELOP_ACCOUNT_ID }}

jobs:
  validate-cfn-templates:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Validate CFN templates
        uses: ./.github/actions/run-cfn-script@main
        with:
          script-file: ./chat-infra/validate_cfn_templates.sh

  test-chatapp-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: patternbox/you-build-it-you-run-it/.github/actions/checkout-with-dotenv@main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: chatapp-infra
        run: |
          npm ci
